# -*- coding: utf-8 -*-
"""practice03.ipynb

Automatically generated by Colaboratory.
"""
#Practice example from lessons provided by https://ml.yah.ac
#Reference: https://opentutorials.org/module/4966

###############################################################################
# 아이리스 품종 분류 실습

# 라이브러리 사용
import tensorflow as tf
import pandas as pd
###########################
# 1.과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

# 종속변수, 독립변수 설정
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape) # data 사용전 구조 체크

###########################
# 2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

###########################
# 3.데이터로 모델 학습(FIT)하기
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

###########################
# 4-1. 모델 이용하기. 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

# 4-2. 모델 이용하기. 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

###########################
# weights & bias 출력
print(model.get_weights())

