# -*- coding: utf-8 -*-
"""practice01.ipynb

Automatically generated by Colaboratory.
"""
#Practice example from lessons provided by https://ml.yah.ac
#Reference: https://opentutorials.org/module/4966

import pandas as pd

#파일들로부터 데이터 불러오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

#데이터 모양으로 확인하기
print(레모네이드.shape)
print(보스턴.shape)
print(아이리스.shape)

#column이름 출력
print(레모네이드.columns)
print(보스턴.columns)
print(아이리스.columns)

독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

print(독립, 종속)

독립 = 보스턴[['crim','zn','indus','chas','nox','rm',
          'age','dis','rad','tax','ptratio','b','lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이','꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)

#각각의 데이터 확인해보기
print(레모네이드.head())
print(보스턴.head())
print(아이리스.head())

###############################################################################
#레모네이드 판매예측 지도학습구현 방법 실습


# 0. 라이브러리 사용
import tensorflow as tf
import pandas as pd 

# 1. 레모네이드 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
print(데이터.columns)
print(데이터.head())

# 2. 종속변수, 독립변수 구분
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

# 3. 모델 만들기
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

# 4. 모델을 학습시키기 (epoch=몇번 학습할지)
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

# 위코드를 4번 반복 실행해서 1이하의 loss를 얻음.
# epochs=1000 loss=~2829, 
# epochs+=1000 loss=~870, 
# epochs+=1000 loss=~36, 
# epochs+=1000 loss=~0.04

# 5. 모델을 이용하기
print(model.predict(독립))
num_of_lemons=15
num_of_lemonades=model.predict([[num_of_lemons]])
print("독립변수: "+str(num_of_lemons)+" 종속변수: "+str(num_of_lemonades))

