# -*- coding: utf-8 -*-
"""practice02.ipynb

Automatically generated by Colaboratory.
"""
#Practice example from lessons provided by https://ml.yah.ac
#Reference: https://opentutorials.org/module/4966

###############################################################################
# 보스턴 집값 예측 지도학습구현 방법 실습

# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 1.과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape) #내가 사용 하려는 데이터의 상태 확인하는것 중요. 실수 방지

# 2. 모델의 구소를 만들기
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

# 3. 데이터로 모델을 학습(fit)하기
model.fit(독립, 종속, epochs=2000, verbose=0)
model.fit(독립, 종속, epochs=10)

# 4. 모델을 이용하기
print(model.predict(독립[0:5]))
print(종속[0:5])

# 모델의 수식 확인
print(model.get_weights())
